server:
  port: 8050
spring:
  application:
    name: zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
zuul:
  routes:
    app-hello:
      path: /user/**
      serviceId: consumer-feign-hystrix
    app-sidercar:
      path: /sidercar/**
      serviceId: sidercar
